---
server:
    install: '1'
    timezone: Africa/Johannesburg
    locale: en_GB.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: suresale.local, ip: 192.168.33.99, memory: '1024', sharedfolder: ./, syncType: '0' }
apache:
    install: '1'
    docroot: /vagrant/
    servername: suresale.local
mysql:
    install: '1'
    root_password: test
    database: db
    user: test
    password: test
    dump: ''
php:
    install: '1'
    ppa: php
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql, php5-gd, php5-curl]
xdebug:
    install: '1'
composer:
    install: '1'

